### PR TITLE
Simplification and python3 support

### PR DESCRIPTION
**Pull request by sijis**
I think this is a neat project, so I spent some time converting it to python3 and simplified a few checks along the way.

The only gotcha about using python3 is support of pycrypto. The only way to really get it working was to install the latest pycrypo as such `pip install https://github.com/dlitz/pycrypto/archive/v2.7a1.zip`.
It does appear the community is moving to `cryptography`.

### CODE REVIEW

**Comment by kushaldas** [comment]
I somehow missed this PR :( Thank you for the great work. We will have to make sure that all of our dependencies are already packaged for Fedora, that means pycrypto (or if you choose to use something else). 
Also please rebase with the master once more (if required), as we are pushing in a few changes.
I will ping you on IRC to have a chat :)

**Comment by sijis** [comment]
I've rebased off `master` branch.
I've running the tests cases and they are failing now. I'll have to spend some time and figure out the actual issues at hand.

As a side node, i did make much more invasive changes in another branch (https://github.com/sijis/tunir/tree/feature/reorg) but I did not want to make a PR from that.

**Comment by sijis** [comment]
Here's what i have on the test cases error.

I was seeing the following randomly running `py.test -k test_multihost tests.py -s` in py2 and py3.
```
>           self.assertEqual(calls[1], vals)
E           AssertionError: Tuples differ: ('192.168.122.102', 22, 'fedora', None, 'sudo su -c"echo Hello > /abcd.txt"') != ('192.168.122.100', 22, 'fedora', None, 'sudo su -c"echo Hello > /abcd.txt"')
E           
E           First differing element 0:
E           '192.168.122.102'
E           '192.168.122.100'
E           
E           - ('192.168.122.102', 22, 'fedora', None, 'sudo su -c"echo Hello > /abcd.txt"')
E           ?                 ^
E           
E           + ('192.168.122.100', 22, 'fedora', None, 'sudo su -c"echo Hello > /abcd.txt"')
E           ?                 ^

tests.py:137: AssertionError
```

It seemed as if the order of the vms was incorrect, meaning test for vm1 was running against vm2.
I've made the following changes and it seems to have stabilized, however I do not know if that changes significant behaviour/functionality

```python
+++ b/tunirlib/tunirmultihost.py
@@ -245,7 +245,7 @@ def start_multihost(jobname, jobpath, debug=False, oldconfig=None, config_dir='.
         pkey = create_rsa_key(private_key)
 
     try:
-        for vm_c in vm_keys:
+        for vm_c in sorted(vm_keys):
             # Now create each vm one by one.
             # Get the current ips
             this_vm = {}
```

I will put a PR on my tox setup.

**Comment by sijis** [comment]
I've added PR #53 to include my tox info.

**Comment by kushaldas** [comment]
I am trying to merge this PR. Have you tried to run the tests with Python2 or Python3 (not py.test but simple Python) ?
```
$ python tests.py

........E
======================================================================
ERROR: test_updateresult (__main__.UpdateResultTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 191, in test_updateresult
    tunirutils.update_result(res, command, negative)
  File "/home/kdas/code/git/tunir/tunirlib/tunirutils.py", line 250, in update_result
    d = {'command': command, 'result': unicode(result),
  File "/home/kdas/code/git/tunir/tunirlib/tunirutils.py", line 45, in __unicode__
    return unicode(self.text, encoding='utf-8', errors='replace')
TypeError: decoding Unicode is not supported

----------------------------------------------------------------------
Ran 9 tests in 0.381s

FAILED (errors=1)

$ python3 tests.py
......E.E
======================================================================
ERROR: test_multihost (__main__.TunirTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/mock.py", line 1159, in patched
    return func(*args, **keywargs)
  File "tests.py", line 128, in test_multihost
    tunirmultihost.start_multihost('multihost', './testvalues/multihost.txt', debug=False, config_dir='./testvalues/')
  File "/home/kdas/code/git/tunir/tunirlib/tunirmultihost.py", line 238, in start_multihost
    private_key, public_key, KEY = generate_sshkey()
  File "/home/kdas/code/git/tunir/tunirlib/tunirmultihost.py", line 85, in generate_sshkey
    public_key = key.publickey().exportKey("OpenSSH")
  File "/usr/lib64/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 352, in exportKey
    keystring = ''.join([ struct.pack(">I",len(kp))+kp for kp in keyparts])
  File "/usr/lib64/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 352, in <listcomp>
    keystring = ''.join([ struct.pack(">I",len(kp))+kp for kp in keyparts])
TypeError: can't concat bytes to str

======================================================================
ERROR: test_updateresult (__main__.UpdateResultTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 191, in test_updateresult
    tunirutils.update_result(res, command, negative)
  File "/home/kdas/code/git/tunir/tunirlib/tunirutils.py", line 250, in update_result
    d = {'command': command, 'result': unicode(result),
NameError: name 'unicode' is not defined

----------------------------------------------------------------------
Ran 9 tests in 0.182s

FAILED (errors=2)
```
I am also thinking to work on top of your commits and make it Python3 only.

**Comment by sijis** [comment]
I have another PR that shows the tox setup I used to validate it.

**Comment by sijis** [comment]
It's PR #53.

**Comment by sijis** [comment]
I had run it locally with calling python3 in a virtualenv.

**Comment by sijis** [comment]
Ohh reminds me, I think I used a pycrypto patch, as that's likely coming from there. When I get home I can double-check.

**Comment by kushaldas** [comment]
I am going to remove pycrypto as dependency and use only cryptography for Python3. I have already merged this PR in my local branch, I will merge to master and then push to github tomorrow. Thank you for the help :) This really pushed me to move to Python3 for tunir.

**Comment by sijis** [comment]
Lol. Awesome! I didn't get a chance to explore cryptography on that respect.
I also hope you find the tox setup helpful.

**Pull request merged**
